CREATE TABLE IF NOT EXISTS United_Airlines_SQL_File (
    Calculated_total_handle_time_per_call TEXT,
    Column_2 INTEGER
);
INSERT INTO United_Airlines_SQL_File VALUES ('SELECT ',NULL),
	('    call_id, ',NULL),
	('    (strftime(''%s'', call_end_datetime) - strftime(''%s'', call_start_datetime)) AS total_handle_time',NULL),
	('FROM calls',NULL),
	(NULL,NULL),
	('-- Calculated overall AHT',NULL),
	('SELECT ',NULL),
	('    SUM(strftime(''%s'', call_end_datetime) - strftime(''%s'', call_start_datetime)) / COUNT(call_id) AS AHT',NULL),
	('FROM calls',NULL),
	(NULL,NULL),
	('-- Calculated total waiting time per call ',NULL),
	('SELECT ',NULL),
	('    call_id, ',NULL),
	('    (strftime(''%s'', agent_assigned_datetime) - strftime(''%s'', call_start_datetime)) AS total_waiting_time',NULL),
	('FROM calls',NULL),
	('WHERE agent_assigned_datetime IS NOT NULL',NULL),
	(NULL,NULL),
	('-- Calculated overall AST',NULL),
	('SELECT ',NULL),
	('    SUM(strftime(''%s'', agent_assigned_datetime) - strftime(''%s'', call_start_datetime)) / COUNT(call_id) AS AST',NULL),
	('FROM calls',NULL),
	('WHERE agent_assigned_datetime IS NOT NULL',NULL),
	(NULL,NULL),
	('-- Merged sentiment and call duration data',NULL),
	('SELECT ',NULL),
	('    s.call_id,',NULL),
	('    s.customer_tone,',NULL),
	('    s.agent_tone,',NULL),
	('    s.average_sentiment,',NULL),
	('    (strftime(''%s'', c.call_end_datetime) - strftime(''%s'', c.call_start_datetime)) AS total_handle_time',NULL),
	('FROM sentiment_statistics s',NULL),
	('JOIN calls c ON s.call_id = c.call_id',NULL),
	(NULL,NULL),
	('-- Checked correlation between sentiment and handle time',NULL),
	('SELECT ',NULL),
	('    AVG((strftime(''%s'', call_end_datetime) - strftime(''%s'', call_start_datetime))) AS avg_handle_time,',NULL),
	('    customer_tone, agent_tone',NULL),
	('FROM sentiment_statistics s',NULL),
	('JOIN calls c ON s.call_id = c.call_id',NULL),
	('GROUP BY customer_tone, agent_tone',NULL),
	(NULL,NULL),
	('-- Listed most frequent call reasons from the reason table',NULL),
	('SELECT r.primary_call_reason, COUNT(c.call_id) AS frequency',NULL),
	('FROM calls c',NULL),
	('JOIN reason r ON c.call_id = r.call_id',NULL),
	('GROUP BY r.primary_call_reason',NULL),
	('ORDER BY frequency DESC',NULL),
	(NULL,NULL),
	('-- Calculated the average handle time (AHT) for each primary call reason',NULL),
	('WITH avg_aht AS (',NULL),
	('    SELECT ',NULL),
	('        AVG(strftime(''%s'', c.call_end_datetime) - strftime(''%s'', c.call_start_datetime)) AS overall_avg_aht',NULL),
	('    FROM calls c',NULL),
	(')',NULL),
	('SELECT ',NULL),
	('    r.primary_call_reason, ',NULL),
	('    AVG(strftime(''%s'', c.call_end_datetime) - strftime(''%s'', c.call_start_datetime)) AS avg_handle_time',NULL),
	('FROM calls c',NULL),
	('JOIN reason r ON c.call_id = r.call_id',NULL),
	('GROUP BY r.primary_call_reason',NULL),
	('HAVING avg_handle_time > (SELECT overall_avg_aht FROM avg_aht)',NULL),
	(NULL,NULL),
	(NULL,NULL),
	('-- Got the average handling time by primary call reason (focused on long AHT)',NULL),
	('SELECT r.primary_call_reason, ',NULL),
	('    COUNT(c.call_id) AS frequency,',NULL),
	('    AVG(strftime(''%s'', c.call_end_datetime) - strftime(''%s'', c.call_start_datetime)) AS avg_handle_time',NULL),
	('FROM calls c',NULL),
	('JOIN reason r ON c.call_id = r.call_id',NULL),
	('GROUP BY r.primary_call_reason',NULL),
	('HAVING avg_handle_time > 1000 ',NULL),
	('ORDER BY avg_handle_time DESC',NULL),
	(NULL,NULL),
	('-- Filtered calls by agent and customer tone that have the highest AHT',NULL),
	('SELECT c.call_id, r.primary_call_reason, s.customer_tone, s.agent_tone,',NULL),
	('    strftime(''%s'', c.call_end_datetime) - strftime(''%s'', c.call_start_datetime) AS handle_time',NULL),
	('FROM calls c',NULL),
	('JOIN reason r ON c.call_id = r.call_id',NULL),
	('JOIN sentiment_statistics s ON c.call_id = s.call_id',NULL),
	('WHERE (s.customer_tone = ''angry'' OR s.agent_tone = ''angry'')',NULL),
	('ORDER BY handle_time DESC',NULL),
	(NULL,NULL),
	(NULL,NULL),
	('-- Identified frequent call reasons associated with negative customer sentiment that can be solved by IVR',NULL),
	('SELECT r.primary_call_reason, ',NULL),
	('    COUNT(c.call_id) AS frequency, ',NULL),
	('    AVG(strftime(''%s'', c.call_end_datetime) - strftime(''%s'', c.call_start_datetime)) AS avg_handle_time,',NULL),
	('    s.customer_tone',NULL),
	('FROM calls c',NULL),
	('JOIN reason r ON c.call_id = r.call_id',NULL),
	('JOIN sentiment_statistics s ON c.call_id = s.call_id',NULL),
	('WHERE s.customer_tone IN (''angry'', ''frustrated'') ',NULL),
	('AND r.primary_call_reason IN (''Seating'', ''Voluntary Change'', ''Post-Flight'')',NULL),
	('GROUP BY r.primary_call_reason, s.customer_tone',NULL),
	('ORDER BY frequency DESC',NULL),
	(NULL,NULL),
	(NULL,NULL),
	(NULL,NULL),
	(NULL,NULL);
